name: time_log
description: Like javascript console.time, console.timeEnd in Dart
version: 0.1.0
author: pillar<ymzuiku@gmail.com>
homepage: https://github.com/ymzuiku/dart-time-log

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

